# Global configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: "development"

# Scrape configuration
scrape_configs:
  - job_name: 'document-analysis'
    scrape_interval: 15s
    static_configs:
      - targets: ['backend:8001']
